'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Attendance
    Public Property Id As Integer
    Public Property [Date] As Date
    Public Property InHour As System.TimeSpan
    Public Property OutHour As Nullable(Of System.TimeSpan)
    Public Property EmployeeCardId As String

    Public Overridable Property Employee As Employee
    Public Overridable Property Justification As ICollection(Of Justification) = New HashSet(Of Justification)

End Class
