'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DBAttendanceEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DBAttendanceEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Attendance() As DbSet(Of Attendance)
    Public Overridable Property Contract() As DbSet(Of Contract)
    Public Overridable Property Employee() As DbSet(Of Employee)
    Public Overridable Property Justification() As DbSet(Of Justification)
    Public Overridable Property License() As DbSet(Of License)
    Public Overridable Property LicenseType() As DbSet(Of LicenseType)
    Public Overridable Property Permission() As DbSet(Of Permission)
    Public Overridable Property Schedule() As DbSet(Of Schedule)
    Public Overridable Property ScheduleDetail() As DbSet(Of ScheduleDetail)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property User() As DbSet(Of User)

End Class
