'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Justification
    Public Property Id As Integer
    Public Property [Date] As Date
    Public Property Motive As String
    Public Property State As Boolean = false
    Public Property AttendanceId As Integer

    Public Overridable Property Attendance As Attendance

End Class
