'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class License
    Public Property Id As Integer
    Public Property PresentationDate As Date
    Public Property StartDate As Date
    Public Property FinishDate As Date
    Public Property State As Boolean = false
    Public Property Document As Byte()
    Public Property EmployeeCardId As String
    Public Property LicenseTypeId As Byte
    Public Property DocumentName As String

    Public Overridable Property Employee As Employee
    Public Overridable Property LicenseType As LicenseType

End Class
