'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ScheduleDetail
    Public Property Id As Integer
    Public Property ScheduleId As Integer
    Public Property Day As Byte
    Public Property InHour As Byte
    Public Property OutHour As Byte

    Public Overridable Property Schedule As Schedule

End Class
